### ISSUE TITLE
Traversability related

### ISSUE THREAD

**Issue by fgsdfgsda** [tudelft/AvoidBench#4]
Hi, in what part of the code is traversability calculated specifically? Appreciate it if you can reply!

**Comment by NPU-yuhang** [comment]
Hi, please refer to:
https://github.com/tudelft/AvoidBench/blob/c85581ec3bd7f961f4ad81582900ce6e38d40b87/src/avoidbench/avoidmetrics/src/environment.cpp#L142

**Comment by fgsdfgsda** [comment]
> Hi, please refer to:
> 
> https://github.com/tudelft/AvoidBench/blob/c85581ec3bd7f961f4ad81582900ce6e38d40b87/src/avoidbench/avoidmetrics/src/environment.cpp#L142

Thanks!
