### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lgh5054** [tudelft/AvoidBench#7]
Thank you for sharing a good source. However, the error below occurs.
RTX4080
Cuda :11.8
g++: 9.4
gcc: 9.4
Cmake --version : 3.21.0

![image](https://github.com/tudelft/AvoidBench/assets/35057391/2f2e5fae-a2f4-4c46-88b7-69955190c9a2)

**Comment by NPU-yuhang** [comment]
Can you please show which ros package the error happened in? I guess you can try to remove the 'external' folder and compile again.

**Comment by lgh5054** [comment]
ThirdP 
agilicious
avoidbench

The same installation file exists in three folders. Therefore, I commented out the rest of the installation files except one and completed the installation.
